---
# tasks file for helabs.passenger-nginx
- include: RedHat.yml
  when:
    ansible_os_family == 'RedHat'

- include: Debian.yml
  when:
    ansible_os_family == 'Debian'

- name: Gathering passenger-config --root facts
  command: passenger-config --root
  changed_when: no
  register: passenger_config_root

- name: Gathering ruby path
  command: which ruby
  changed_when: no
  register: passenger_which_ruby

- name: Gathering facts for passenger config
  set_fact:
    passenger_root: "{{ passenger_config_root.stdout | trim }}"
    passenger_ruby: "{{ passenger_which_ruby.stdout | trim }}"

- name: Enabling passenger
  template:
    src: passenger.conf.j2
    dest: /etc/nginx/conf.d/passenger.conf
    mode: 0644
    owner: root
    group: root
  notify: reload nginx

- name: Configuring nginx
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    mode: 0644
    owner: root
    group: root
  notify: reload nginx


- name: Configuring nginx vhost
  template:
    src: app.conf.j2
    dest: "/etc/nginx/sites-available/{{ passenger_app_name }}"
    mode: 0644
    owner: root
    group: root
  notify: reload nginx

- name: app - enable site conf
  file:
    src: "/etc/nginx/sites-available/{{ passenger_app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ passenger_app_name }}"
    mode: 0644
    owner: root
    group: root
    state: link
  notify: reload nginx
